### PR TITLE
Kafka risingwave

### PR DESCRIPTION
**Pull request by xdgrulez**
Hi Simon,

ich habe die letzten Tage endlich Zeit gefunden, um mich hinzusetzen und meinen "Tech Stack" zu schreiben. Eine erste Version habe ich jetzt fertig - lass' mich wissen, was ich noch anpassen sollte :)

Viele Grüße,
Ralph

### CODE REVIEW

**Comment by jochenchrist** [comment]
@xdgrulez 
Thanks for your contribution.

I would suggest adding a contribution box like the yellow box on https://www.datamesh-architecture.com/tech-stacks/sap to this tech stack.

**Comment by jochenchrist** [comment]
In general, a bit too many "bold" sentences IMHO, but nothing that prevents merging.

**Comment by xdgrulez** [comment]
Added info box now - as for the heavy use of boldface we can still work on this :)

**Comment by simonharrer** [comment]
@xdgrulez can you have a look and remove the amount of bold-face elements. Perhaps reduce it to 1 or 2 per paragraph? I think we should plan to release on thursday afternoon. I'll have a look what we need otherwise.

**Comment by simonharrer** [comment]
Udn wir sind live

**Comment by simonharrer** [comment]
Danke an alle für eure Mithilfe, insbesondere an @xdgrulez für den tollen Content. :-)

**Comment by xdgrulez** [comment]
Danke an euch, war mir eine Ehre :-)

**Pull request merged**
